image: gbraad/docugen:latest

pages:
  script:
  - pandoc -t html5 --template template/reveal-slides-template.html --standalone --section-divs -o index.html ./md/index.md
  - pandoc -t html5 --template template/reveal-slides-template.html --standalone --section-divs -o 01-introduction.html ./md/01-introduction.md
  - pandoc -V geometry:margin=1in -o 01-introduction.pdf ./md/01-introduction.md
  - pandoc -t html5 --template template/reveal-slides-template.html --standalone --section-divs -o 02-cultural-aspects.html ./md/02-cultural-aspects.md
  - pandoc -V geometry:margin=1in -o 02-cultural-aspects.pdf ./md/02-cultural-aspects.md
  - pandoc -t html5 --template template/reveal-slides-template.html --standalone --section-divs -o 03-communities.html ./md/03-communities.md
  - pandoc -V geometry:margin=1in -o 03-communities.pdf ./md/03-communities.md
  - pandoc -t html5 --template template/reveal-slides-template.html --standalone --section-divs -o 04-contributing.html ./md/04-contributing.md
  - pandoc -V geometry:margin=1in -o 04-contributing.pdf ./md/04-contributing.md
  - pandoc -t html5 --template template/reveal-slides-template.html --standalone --section-divs -o 05-git-and-gerrit.html ./md/05-git-and-gerrit.md
  - pandoc -V geometry:margin=1in -o 05-git-and-gerrit.pdf ./md/05-git-and-gerrit.md
  - pandoc -t html5 --template template/reveal-slides-template.html --standalone --section-divs -o 06-vim-editor.html ./md/06-vim-editor.md
  - pandoc -V geometry:margin=1in -o 06-vim-editor.pdf ./md/06-vim-editor.md
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
